MOOD_BUTTON = "Случайное воспоминание 📷"
FAVORITE_BUTTON = "Любимое фото 💛"
RELATIONSHIP_BUTTON = "Сколько мы вместе? ⏳"
ADD_WISH_BUTTON = "Добавить желание 🎁"
WISHLIST_BUTTON = "Мой список 📝"
QUIZ_BUTTON = "Личный квиз 🎲"
HELP_BUTTON = "Справка ℹ️"
ABOUT_BUTTON = "О CareNest"

SUPPORT_TEXT = "Пусть это небольшое воспоминание сделает день чуть теплее."
FAVORITE_TEXT = "Одно из самых любимых фото — пусть напомнит о хорошем."
FAVORITE_FALLBACK_TEXT = "Любимые фото пока недоступны, но тёплое настроение всегда с тобой."
